apiVersion: v1
kind: Service
metadata:
  name: gucci
spec:
  type: NodePort
  selector:
    app: gucci-test
    env: v1
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 31000
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: gucci-test
spec:
   replicas: 1
   selector: 
     matchLabels:
       app: gucci-test
       env: v1
   template:
     metadata:
       labels:
         app: gucci-test
         env: v1
     spec:
       containers:
       - name: gucci-test
         image: ${IMAGE}
         ports:
         - name: httpd
           containerPort: 8080
